### ISSUE TITLE
Elaborate HELP description

### ISSUE THREAD

**Issue by shishir-a412ed** [willmtemple/graphc#1]
@willmtemple 

Can we have a more elaborate HELP Description on how to build this CLI tool ?
Right now I did a `git clone git@github.com:willmtemple/graphc.git`
and tried `graphc --help` which says graphc command not found.

Need more extensive description on how to build the binary.
Some examples would be useful.

**Comment by willmtemple** [comment]
@shishir-a412ed If you pull the repo and build with `go build /path/to/graphc` then the binary will be generated in the same folder you checked out to.

Alternatively, if you check the repo out with `go get github.com/willmtemple/graphc` it will build the binary for you and place it in `${GOPATH}/bin`.

I will update the README accordingly.
